source "https://rubygems.org"
gem 'sinatra'
gem 'pony'
gem 'rerun'
gem 'clockwork'
gem 'i18n'
gem 'redis'
gem 'cssmin'
gem 'jsmin'
gem 'sinatra-cache'
gem 'mini_magick'
gem 'thin'
gem 'chartkick'
gem 'foreman'
gem 'oauth2'
gem 'json'
gem 'sinatra-session'
gem 'sinatra-flash'
gem 'sinatra-partial'
gem 'bluecloth'
gem 'haml'
gem 'mysql2'
gem 'sequel'
gem 'sidekiq'
gem 'bcrypt'

group :test do
	gem 'ZenTest'
	gem 'rspec'
  gem 'rspec-autotest'
  gem 'rb-fsevent'
  gem 'autotest-growl'
  gem 'autotest-fsevent'
	gem 'rack-test'
	gem 'capybara'
end

