source "https://rubygems.org"
gem 'sinatra'
gem 'clockwork'
gem 'redis'
gem 'lazy_high_charts'
gem 'mini_magick'
gem 'thin'
gem 'groupdate'
gem 'chartkick'
gem 'foreman'
gem 'oauth2'
gem 'json'
gem 'sinatra-session'
gem 'sinatra-flash'
gem 'sinatra-partial'
gem 'bluecloth'
gem 'haml'
gem 'mysql2'
gem 'sequel'
gem 'sidekiq'
gem 'bcrypt'

group :test do
	gem 'rspec'
	gem 'rack-test'
	gem 'ZenTest'
	gem 'autotest-fsevent'
	gem 'autotest-growl'
	gem 'capybara'
end

